Fix import of ZEO.ClientStorage
I got an error message like this:

```Module experimental.gracefulblobmissing.patches, line 146, in patched_loadBlob
AttributeError: type object 'ClientStorage' has no attribute '_accessed'```

I think we just need to fix the import. It now works locally and I also looked at the current version in zopefoundation/ZEO. As far as I can tell this change should still be valid.